---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment # Changed name for clarity, though 'myapp' is fine if consistent
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # This MUST match the image name used in your Jenkinsfile's docker.build step
        # If your Jenkinsfile builds 'dockerhubdemos/devops', it should be:
        image: dockerhubdemos/devops:tagversion 
        ports:
        - containerPort: 8080
